# NUMPY 

In [ ]:
NumPy is a Python library used for working with arrays
NumPy stands for Numerical Python.
It is the fundamental package for scientific computing with Python.

# install numpy

In [6]:
!pip install numpy

# importing numpy library

In [7]:
import numpy as np

creating array using .array() method

In [141]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

type of array

In [142]:
type(arr)

numpy.ndarray

Data type of array

In [11]:
arr.dtype

dtype('int32')

2D array# we can identity by seeing [[  these brackets

In [18]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])#it is a 2d array
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

shape of array

In [19]:
b.shape#it is 3*3means 3 rows and 3 columns

(3, 3)

In [23]:
#ex 2
c = np.array([[1,2,3],[4,5,6]])# it is 2 rows and 3 columns
c

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
d = np.array([1,2])# it is 1 row and 2 columns
d

array([1, 2])

In [26]:
#numpy will do elementwise calculations
list = [i for i in range(10)]# simply list
list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [55]:
arr = np.arange(10)#above list is same but we use array function for speed
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr = arr+2#here we are adding above array here by using addition
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [57]:
timeit [i**2 for i in range(10000)]#here time which takes list to execute

5.09 ms ± 241 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [58]:
timeit np.array(10000)**2 # here time which takes numpy array to execute

2.12 µs ± 50.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [50]:
np.zeros([3,5])# it displays rows and columns in the float type

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
np.zeros([3,4],dtype = np.int32)# to get in the form of int

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [59]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
np.ones([3,5],dtype = np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [83]:
np.ones(1,dtype = np.int32)#vector

array([1])

In [84]:
np.ones([2,3],dtype = np.int32)#matrix

array([[1, 1, 1],
       [1, 1, 1]])

In [70]:
np.zeros_like(b)#here it displays the same rows and colums above given b 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
np.ones_like(c)#here it display the same rows and colums above given c

array([[1, 1, 1],
       [1, 1, 1]])

In [74]:
np.full((3,5),6)#it displays 3 rows and 5colums with number 6

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [81]:
np.eye(3)#these method used to create identity matrix,here m=n

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
np.eye(3,dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

To create diagonal matrix

In [86]:
np.diag([2,3])#to create diagonal matrix

array([[2, 0],
       [0, 3]])

In [98]:
np.diag(np.arange(1,10,2))#it is also works on step function

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 7, 0],
       [0, 0, 0, 0, 9]])

Accessing and Slicing Numpy array elements
1D arrays

In [100]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a[0]

1

In [103]:
a[-1]

9

In [104]:
a[2:6]

array([3, 4, 5, 6])

In [105]:
a[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [106]:
a[::2]

array([1, 3, 5, 7, 9])

In [107]:
a[0:8:2]

array([1, 3, 5, 7])

In [108]:
a[::-2]

array([9, 7, 5, 3, 1])

n-dimesion array

In [112]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])#it is some tricky
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
#to access 3
a[0,2]

3

In [114]:
#to access 11
a[2,2]

11

In [117]:
#toaccess 14
a[3,1]

14

In [125]:
# to access 6,7,10,11
a[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [126]:
a[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [128]:
a[2:4,0:2]

array([[ 9, 10],
       [13, 14]])

In [129]:
a[0:2,2:4]

array([[3, 4],
       [7, 8]])

In [134]:
a[1:3,0:2]

array([[ 5,  6],
       [ 9, 10]])

In [135]:
a[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [136]:
a[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [137]:
a[1:3,2:4]

array([[ 7,  8],
       [11, 12]])