In [72]:
import numpy as np

In [73]:
print(np.random.random())#to get some random elements

0.7099478870139949


In [74]:
a = np.random.seed(10)#were ouput is stored 

In [75]:
a = np.random.randint(low = 10,high = 100)
a

19

In [76]:
a = np.random.random(3)
a

array([0.29876115, 0.49458993, 0.44301495])

In [77]:
a = np.random.random((3,3))
a

array([[0.83191136, 0.58332174, 0.02517173],
       [0.70920801, 0.26556613, 0.26360285],
       [0.15037787, 0.68381843, 0.81660184]])

In [78]:
a = np.random.randint(low = 10,high = 100,size = (3,3))#randit select integer from low to high in within the size
a

array([[21, 64, 98],
       [72, 43, 82],
       [88, 59, 61]])

In [79]:
a = [1,2,3,4,5]
np.random.choice(a,size = 3)

array([4, 2, 5])

In [80]:
a = [1,2,3,4,5,6,7,8,9]
np.random.choice(a,size = 10)

array([7, 2, 5, 3, 7, 8, 9, 9, 3, 1])

In [81]:
a = np.random.random((4,4))
a

array([[0.41118255, 0.0768555 , 0.85304299, 0.43998746],
       [0.12195415, 0.73173462, 0.13878247, 0.76688005],
       [0.83198977, 0.30977806, 0.59758229, 0.87239246],
       [0.98302087, 0.46740328, 0.87574449, 0.2960687 ]])

In [82]:
r = np.round(a,3)#it gives decimal value
r

array([[0.411, 0.077, 0.853, 0.44 ],
       [0.122, 0.732, 0.139, 0.767],
       [0.832, 0.31 , 0.598, 0.872],
       [0.983, 0.467, 0.876, 0.296]])

In [83]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [6]:
import numpy as np
my_list =[1,2,3,4,5]
arr=np.array(my_list)
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
arr.shape

(5,)

In [52]:
my_list1 = [1,2,3,4]
my_list2 = [5,6,7,8]
my_list3 = [9,10,11,12]
my_list4 = [13,14,15,16]
my_list5 = [17,18,19,20]
arr =np.array([my_list1,my_list2,my_list3,my_list4,my_list5])

In [53]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [54]:
type(arr)

numpy.ndarray

In [55]:
arr.shape

(5, 4)

In [56]:
arr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [57]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [58]:
arr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [60]:
arr[3:]=100
arr

array([[  1,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])