# Replace Function

In [17]:
import numpy as np
import pandas as pd

In [18]:
df = pd.Series([1,2,3,4,5,6,7,8,9])
df

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [43]:
df1 = df.replace(1,100)#replacing with single values
df1


0    100
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
dtype: int64

In [44]:
df2 = df1.replace(2,50)
df2

0    100
1     50
2      3
3      4
4      5
5      6
6      7
7      8
8      9
dtype: int64

In [46]:
df3 = df2.replace(8,200)
df3

0    100
1     50
2      3
3      4
4      5
5      6
6      7
7    200
8      9
dtype: int64

In [47]:
df

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [48]:
df1 = df.replace({1:100,2:50})#replacing with multiple values
df1

0    100
1     50
2      3
3      4
4      5
5      6
6      7
7      8
8      9
dtype: int64

In [36]:
df1.replace({3:20,5:30,8:35,9:25})

0    100
1     50
2     20
3      4
4     30
5      6
6      7
7     35
8     25
dtype: int64

In [2]:
from sklearn import preprocessing

In [3]:
le = preprocessing.LabelEncoder()
le.fit([1,2,2,6])

LabelEncoder()

In [5]:
le.classes_

array([1, 2, 6])

In [6]:
le.transform([1, 1, 2, 6])

array([0, 0, 1, 2], dtype=int64)

In [7]:
le.inverse_transform([0, 0, 1, 2])

array([1, 1, 2, 6])